name: Submit a challenge application
description: File a challenge template for Specify team.
title: Challenge application from [your-company-name]
labels: "✨ New"
assignees: annawillems, ChucKN0risK, nclsndr
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your time filling this issue...
  - type: textarea
    id: process-description
    attributes:
      label: Design to code process
      description: Can you describe the design to code process you'd like to handle?
      value: |
        On the design side, we use Figma...
        On the frontend side, we expect the design tokens to be delivered...
    validations:
      required: true
  - type: input
    id: file-extension
    attributes:
      label: Output file extension
      description: Which extension is your output file?
      placeholder: .css
    validations:
      required: true
  - type: textarea
    id: file-content
    attributes:
      label: Output file content
      description: What content do you expect in your developement environement ?
      value: ""
    validations:
      required: true
